### ISSUE TITLE
add option to save session

### ISSUE THREAD

**Issue by marcmo** [esrlabs/logviewer#224]
saving the file only will loose information (e.g. all the bookmarks, all the highlights).
we should provide a way to completely restore a session

**Comment by DmitryAstafyev** [comment]
With logs can be bound:
a) search requests (filters)
b) bookmarks
c) markers

From 0.23.0 logviewer exports logs into file with (a) and (b). Injection of markers doesn't look at the moment as a good idea, because a user will be confused with removing imported markers. For example, bookmarks are bound with log data and will be reset with opening new stream/file. Filters are present in the main view and imported filters can be removed by 2 clicks. But markers excluded into settings and the user (which never uses markers) will be confused with searching a way to remove it.
