### ISSUE TITLE
Support running `rogcat`

### ISSUE THREAD

**Issue by flxo** [esrlabs/logviewer#245]
# Prerequisites

affected version:  0.28.2

make sure to check this before filing an issue:

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior

Running [rogcat](https://github.com/flxo/rogcat) for better readability then plain `adb logcat` should work.

# Current Behavior

`logviewer silently fails to execute.

## Steps to Reproduce

Run `rogcat --color never`

## Context

* Operating System: macos

@dmitry.astafyev: we already talked about this issue. Looks like something in the environment where external commands are called in.

**Comment by DmitryAstafyev** [comment]
Confirm. There is a problem with env. It was missed because for testing logviewer is started from the terminal (to see logs and output) and from terminal it works. Probably electron "change" somehow env if an application started in a regular way. 

I've reopened an issue.

**Comment by DmitryAstafyev** [comment]
Fixed with 0.29.1. The issue was: rogcat wouldn't start without "TERM" variable in the environment; logviewer doesn't care about this variable. In some cases it could be defined, in some - not: depends how logviewer was executed. Logviewer has now default value for this variable "xterm-256color". 

But probably rogcat can have issues with executing in some other cases because it strictly depends on TERM variable. Probably rogcat also should have some default value of TERM for cases when it wasn't defined on environment level. For example "adb logcat" can be executed without any issues even TERM isn't defined.

**Comment by DmitryAstafyev** [comment]
And one for remark. Obviously rogcat depends on adb sdk. If adb sdk has beed installed in some custom location attempt to execute rogcat will be failed for sure. To prevent it addition path should be defined.

![screen shot 2018-10-08 at 10 39 13](https://user-images.githubusercontent.com/12843747/46599112-a8ea0d00-cae6-11e8-8ea5-f6d79742d57b.png)

To split paths use ":" (unix) or ";" (win)
